ALTER TABLE traces {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS framework_skill
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};

ALTER TABLE traces {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS framework_name
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};

ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS mcp_tool
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};

ALTER TABLE observations {CLICKHOUSE_CLUSTER_CLAUSE}
  DROP COLUMN IF EXISTS mcp_name
 {CLICKHOUSE_CLUSTERED_ONLY: SETTINGS alter_sync = 2};
